### ISSUE TITLE
don't build on Linux (Ubuntu 18.04, Kernel 5.3) GCC 7.5 - не компилируется в линуксе. Не сказано какие пакеты нужны!!! С++ как ни странно нужен

### ISSUE THREAD

**Issue by kmwork** [KotskinKotskin/camunda-excamad#1]
/home/lin/.node-gyp/13.11.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/lin/.node-gyp/13.11.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/lin/.node-gyp/13.11.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
binding.target.mk:131: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: выход из каталога «/home/lin/work-lanit/camunda-excamad-master/node_modules/node-sass/build»
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/lin/work-lanit/camunda-excamad-master/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-42-generic
gyp ERR! command "/usr/bin/node" "/home/lin/work-lanit/camunda-excamad-master/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/lin/work-lanit/camunda-excamad-master/node_modules/node-sass
gyp ERR! node -v v13.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.2.1 (node_modules/watchify/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@github:pipobscure/fsevents#7dcdf9fa3f8956610fd6f69f72c67bace2de7138: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

[kostya_versions.txt](https://github.com/KotskinKotskin/camunda-excamad/files/4340282/kostya_versions.txt)
[kostya-try-build_on_console.log](https://github.com/KotskinKotskin/camunda-excamad/files/4340283/kostya-try-build_on_console.log)
[2020-03-16T20_20_37_120Z-debug.log](https://github.com/KotskinKotskin/camunda-excamad/files/4340284/2020-03-16T20_20_37_120Z-debug.log)

**Comment by kmwork** [comment]
если кратко — только вин и мак поддерживается, как понял, печаль, так как -  на бою однозначно не нужен ни вин и ни мак   — **НУЖНА поддержка линуха**

**Comment by koltyakov** [comment]
Для Node v13 не опубликован прекомпилированная нативная зависимость node-sass. Чтобы node-sass скачался без локальной компиляции можно задаунгрейдить версию ноды хотя бы до 12. Либо на билд машине ставить пререквизиты, необходимые для сборки node-sass. Очевидно же! :)

**Comment by kmwork** [comment]
перекомплил на nodejs 12 -- та же ошибка
[kostya_versions_node_js_12.txt](https://github.com/KotskinKotskin/camunda-excamad/files/4342112/kostya_versions_node_js_12.txt)
[kostya-try-build_on_console_node_js_12.log](https://github.com/KotskinKotskin/camunda-excamad/files/4342113/kostya-try-build_on_console_node_js_12.log)
[2020-03-17T07_17_13_535Z-debug.log](https://github.com/KotskinKotskin/camunda-excamad/files/4342114/2020-03-17T07_17_13_535Z-debug.log)

**Comment by koltyakov** [comment]
А, понятно. В excamad зависимость node-sass 4.9, [ее собирали](https://github.com/sass/node-sass/releases?after=v4.10.0) до 10ки. 

И кстати, это dev зависимость, она в рантайме не нужна. Т.е. собирать можно в любом другом рантайме, а потом деплоить в линуксы.

Либо можно в клоне обновить версию node-sass до последней `npm i -D node-sass`, а после чего уже билдить.

**Comment by KotskinKotskin** [comment]
я поправлю версии зависимостей, спасибо.

**Comment by KotskinKotskin** [comment]
@kmwork пофиксил, проверь

**Comment by kmwork** [comment]
да все ок если не считать варинги - напрягают, так как сам как программист считаю варинги желательно тоже фиксить -- признак хорошего кодинга

========================
<pre>&gt; node-sass@4.13.1 postinstall /home/lin/work-lanit/denis_kotov_camunda/camunda-excamad/node_modules/node-sass
&gt; node scripts/build.js

Binary found at /home/lin/work-lanit/denis_kotov_camunda/camunda-excamad/node_modules/node-sass/vendor/linux-x64-72/binding.node
Testing binary
Binary is fine
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">optional</font> SKIPPING OPTIONAL DEPENDENCY: fsevents@0.2.1 (node_modules/watchify/node_modules/fsevents):
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">notsup</font> SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@github:pipobscure/fsevents#7dcdf9fa3f8956610fd6f69f72c67bace2de7138: wanted {&quot;os&quot;:&quot;darwin&quot;,&quot;arch&quot;:&quot;any&quot;} (current: {&quot;os&quot;:&quot;linux&quot;,&quot;arch&quot;:&quot;x64&quot;})
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">optional</font> SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">notsup</font> SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {&quot;os&quot;:&quot;darwin&quot;,&quot;arch&quot;:&quot;any&quot;} (current: {&quot;os&quot;:&quot;linux&quot;,&quot;arch&quot;:&quot;x64&quot;})

</pre>

[after-fix-on-console.log](https://github.com/KotskinKotskin/camunda-excamad/files/4344565/after-fix-on-console.log)
![after-fix](https://user-images.githubusercontent.com/40819387/76878984-a9173c00-6886-11ea-9a14-c20216710d28.png)

**Comment by KotskinKotskin** [comment]
когда-нибудь и до них доберусь)
