### ISSUE TITLE
Feature request: Heatmap like in Cockpit Enterprise

### ISSUE THREAD

**Issue by ykcycer** [KotskinKotskin/camunda-excamad#10]
Ability to see process Heatmap like in Cockpit Enterprise
https://docs.camunda.org/manual/latest/webapps/cockpit/bpmn/process-history-views/#heatmap

**Comment by KotskinKotskin** [comment]
Hi @ykcycer , sorry it is impossible. Camunda Optimaize use  elastic to store information about paths and history of procesess.  I cant do anything like that becouse excamad is servless.
