### ISSUE TITLE
camunda REST processEngine id question

### ISSUE THREAD

**Issue by AleksandrGilmanov** [KotskinKotskin/camunda-excamad#14]
I've found that our camunda instance uses rest base path like 
```
/camunda/api/engine/engine/processEngine([a-zA-z0-9]+)
```
to get processEngine ID we can go to the 
```
/camunda/api/engine/engine
```

It looks like this application uses another paths scheme. I've found mention camunda network configuration or network devices changes. Is it about that?

Can you add some info to README about that?

**Comment by KotskinKotskin** [comment]
add info to readme:

# 0.1 Default camunda rest endpoint

For embedded camunda - ${baseurl}/rest
For standalone camunda - ${baserurl}/engine-rest

Excamad work with default rest api, not cockpit api. So you havent auth user in your context.
