### ISSUE TITLE
npm install stuck 12hour.

### ISSUE THREAD

**Issue by nixwins** [KotskinKotskin/camunda-excamad#26]
after cloning i run npm install get stuck.
![Screenshot_4](https://user-images.githubusercontent.com/8962295/111428439-b1b48380-8721-11eb-8afb-aec826164a66.png)

**Comment by KotskinKotskin** [comment]
hi , seems it`s not excamad problem.  You can find solution like https://stackoverflow.com/questions/16873973/npm-install-hangs

**Comment by nixwins** [comment]
> hi , seems it`s not excamad problem. You can find solution like https://stackoverflow.com/questions/16873973/npm-install-hangs

ty man. I solved this problem. but get now another.

E:\jsprojects\camunda-excamad>**npm run build**

> ex-cam-ad@0.1.0 build E:\jsprojects\camunda-excamad
> vue-cli-service build

|  Building for production...

 ERROR  Failed to compile with 7 errors                                                                      10:57:54 PM

This dependency was not found:

* @/store/store in ./src/api/api.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/noConnect.vue?vue&type=script&lang=js& and 4 others

To install it, you can run: npm install --save @/store/store


This relative module was not found:

* ./store/store in ./src/main.js
 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ex-cam-ad@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ex-cam-ad@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nixwins\AppData\Roaming\npm-cache\_logs\2021-03-17T16_57_54_721Z-debug.log

E:\jsprojects\camunda-excamad>

**Comment by KotskinKotskin** [comment]
Rebase on master, i fixed this.
