### ISSUE TITLE
Cannot show variables for history process instances

### ISSUE THREAD

**Issue by moonheart** [KotskinKotskin/camunda-excamad#37]
Varaibles for histroy process instances are avaliable at /history/variable-instance?processInstanceIdIn=${processInstanceId}

**Comment by KotskinKotskin** [comment]
Hi, thanks for issue.

Can you please clarify what exactly didnt work and what you expect?

Some screenshots will be helpful.

**Comment by moonheart** [comment]
Sorry for late reply,  for a historic process instance, the Variables section should show all its variables, but it didn't.

![image](https://user-images.githubusercontent.com/15916990/146627039-8fba6b09-3597-4247-92ea-2c98349e130a.png)

I found the issue is in the method `VariableList.vue:getVariables` and temporally added a workaround.  It checks variable count and if there is no variables, it checks for historic variables. 

I'm not familiar with frontend development  so I'm sorry I can' send a PR.
