### ISSUE TITLE
Nginx uses priveleged port 80 container don`t working

### ISSUE THREAD

**Issue by omeshcheryakov** [KotskinKotskin/camunda-excamad#40]
Nginx uses priveleged port 80 container don`t working, some logs from container:
`camunda-excamad_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
camunda-excamad_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
camunda-excamad_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
camunda-excamad_1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
camunda-excamad_1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
camunda-excamad_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
camunda-excamad_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
camunda-excamad_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
camunda-excamad_1  | 2022/01/27 10:55:44 [emerg] 1#1: bind() to 0.0.0.0:80 failed (13: Permission denied)
camunda-excamad_1  | nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission   ##denied)`
Change port to 8080 resolves this issue #39

**Comment by KotskinKotskin** [comment]
thanks, closed due to #39
