### ISSUE TITLE
Providing baseurl to docker container

### ISSUE THREAD

**Issue by vitalyzhakov** [KotskinKotskin/camunda-excamad#47]
Hello!

Thanks for your work!

We have run
```
docker run -d -p -e baseurl=xxx.ru 8080:8080 kotovdenis/excamad:latest
```
But requests to API sending to localhost.

How we can modify `baseurl` using docker container?

**Comment by KotskinKotskin** [comment]
Hi! what you want to achieve?  URL for your backends you need enter manually in UI, menu settings

**Comment by vitalyzhakov** [comment]
Ok, thank you.
Now it is not clear.
