### ISSUE TITLE
Can't connect to camunda empty server

### ISSUE THREAD

**Issue by Artidv1** [KotskinKotskin/camunda-excamad#49]
Hi, i try connect to empty camunda server, installed on the same host with url http://host-ip:8080/camunda/engine-rest/engine and http://host-ip:8080/camunda/ and http://host-ip:8080/camunda/engine and http://host-ip:8080/camunda/rest but camunda not works with error 404. How  can i connect to camunda? Camunda running via docker

**Comment by KotskinKotskin** [comment]
Hi. According to that document - URL to rest-api  is **http://localhost:8080/engine-rest**

You can check is that work by simple get request http://localhost:8080/engine-rest/engine . Is that work?

**Comment by Artidv1** [comment]
I was try http://localhost:8080/engine-rest/engine and http://localhost:8080/engine-rest, but same 404 error

**Comment by KotskinKotskin** [comment]
Sorry to hear that, looks like you need configure rest API for Camunda - you can find out information about that in Camunda documentation
