### ISSUE TITLE
Basic authorization fix

### ISSUE THREAD

**Issue by krutoystas** [KotskinKotskin/camunda-excamad#9]
https://github.com/KotskinKotskin/camunda-excamad/blob/a8971ec52cbf60ea17ebf418e4dabb0a273563eb/src/api/api.js#L22

pls add 'Basic ' prefix to Authorization header: api.defaults.headers.common['Authorization'] = 'Basic ' + hash;

**Comment by KotskinKotskin** [comment]
Done in v1.7
